const WHATSAPP_NUMBER = 'XXXXXXXXXX'; // Reemplazar por el número real, código de país + número.
const defaultMessage = 'Hola, AURITIKA EXPERIENCE. Estoy interesado en uno de sus tours y quisiera recibir información.';
const tours = [
  {name:'City Tour Cusco',label:'Cultura & Historia',duration:'1 día',difficulty:'Fácil',altitude:'3,500 m s. n. m.',image:'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=900&q=85',desc:'Recorre los principales atractivos históricos y arqueológicos de Cusco, combinando ciudad, cultura andina y vestigios incas.',places:'Cusco, Qorikancha, Sacsayhuamán, Qenqo, Puca Pucara y Tambomachay'},
  {name:'Valle Sagrado Tradicional',label:'Cultura & Paisaje',duration:'Full Day',difficulty:'Fácil',altitude:'Variable',image:'https://images.unsplash.com/photo-1531968455001-5c5272a41129?auto=format&fit=crop&w=900&q=85',desc:'Una jornada entre arqueología, paisajes, comunidades y gastronomía andina.',places:'Chinchero, Salineras de Maras, Moray, Ollantaytambo, Pisac y Urubamba'},
  {name:'Valle Sagrado VIP + Conexión',label:'Experiencia VIP',duration:'Full Day +',difficulty:'Fácil',altitude:'Variable',image:'https://images.unsplash.com/photo-1478827536114-da961b7eaa54?auto=format&fit=crop&w=900&q=85',desc:'Una experiencia premium por el Valle Sagrado, ideal para enlazar con Machu Picchu.',places:'Chinchero, Maras, Moray, Urubamba, Ollantaytambo y Pisac'},
  {name:'Valle Sagrado VIP',label:'Experiencia VIP',duration:'Full Day',difficulty:'Fácil',altitude:'Variable',image:'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?auto=format&fit=crop&w=900&q=85',desc:'Un ritmo más cómodo, atención personalizada y tiempo para contemplar cada paisaje.',places:'Valle Sagrado de los Incas'},
  {name:'Machu Picchu',label:'Destino imperdible',duration:'1–2 días',difficulty:'Fácil',altitude:'2,430 m s. n. m.',image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=900&q=85',desc:'El viaje soñado: tren, Aguas Calientes, visita guiada y tiempo para conectar con la ciudadela.',places:'Cusco, tren panorámico, Aguas Calientes y Machu Picchu'},
  {name:'Laguna Humantay',label:'Trekking',duration:'1 día',difficulty:'Alta',altitude:'4,200 m s. n. m.',image:'https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=900&q=85',desc:'Una de las rutas naturales más impresionantes de Cusco, con una laguna de intenso color turquesa.',places:'Mollepata, Soraypampa y Laguna Humantay'},
  {name:'Montaña de Colores',label:'Aventura',duration:'1 día',difficulty:'Alta',altitude:'~5,200 m s. n. m.',image:'https://images.unsplash.com/photo-1509233725247-49e657c54213?auto=format&fit=crop&w=900&q=85',desc:'Un paisaje que parece pintado por la naturaleza, en el corazón de los Andes.',places:'Cusipata, mirador y Montaña de 7 Colores'},
  {name:'Montaña de Colores + Cuatrimotos',label:'Aventura + Adrenalina',duration:'Consultar',difficulty:'Alta',altitude:'~5,200 m s. n. m.',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=900&q=85',desc:'Aventura, velocidad y paisajes increíbles de los Andes. Consulta disponibilidad y modalidad.',places:'Paisajes andinos y Montaña de Colores'},
  {name:'Waqrapukara',label:'Trekking & Aventura',duration:'Full Day',difficulty:'Alta',altitude:'Consultar',image:'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&w=900&q=85',desc:'Una aventura a una sorprendente formación rocosa, con caminata y vistas panorámicas.',places:'Waqrapukara y paisajes naturales de Cusco'}
];
const faq = [
  ['¿Cómo puedo viajar a Machu Picchu desde Cusco?','Existen recorridos de 1 día, opciones de 2 días pasando la noche en Aguas Calientes y rutas de caminata. También puedes combinar Cusco, Valle Sagrado y otros atractivos según el tiempo disponible.'],
  ['¿Cuál es la mejor forma de viajar a Machu Picchu desde Cusco?','Para un día, el recorrido combina transporte terrestre, tren y autobús. Con dos días puedes descansar en Aguas Calientes y disfrutar de un itinerario más pausado.'],
  ['¿Cuánto cuesta un viaje a Machu Picchu desde Cusco?','El precio varía según la fecha, disponibilidad de entradas, categoría del tren y servicios elegidos. Consúltanos directamente para recibir una cotización actualizada.'],
  ['¿Qué circuito de Machu Picchu me conviene elegir?','El circuito adecuado depende de la experiencia que buscas y la disponibilidad. El Circuito 2 suele ser una alternativa muy completa para una primera visita.'],
  ['¿Con cuánta anticipación debo reservar?','Recomendamos planificar con varios meses de anticipación, especialmente durante temporada alta o si buscas circuitos y horarios de mayor demanda.'],
  ['¿Puedo visitar Machu Picchu en un día desde Cusco?','Sí. Se inicia temprano con el traslado a la estación de tren, el viaje hasta Aguas Calientes y el ascenso en bus. Después de la visita se retorna a Cusco.'],
  ['¿Qué diferencia hay entre un viaje de 1 día y uno de 2 días?','El viaje de 1 día concentra traslados y visita en una sola jornada. El de 2 días permite pasar la noche en Aguas Calientes y visitar la ciudadela con más calma.'],
  ['¿Qué paquetes combinan Cusco, Valle Sagrado y Machu Picchu?','Podemos ayudarte a planear experiencias que combinen Cusco, Valle Sagrado, Machu Picchu y otros destinos como Laguna Humantay o Montaña de Colores.']
];
function waLink(message = defaultMessage) { return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`; }
document.querySelectorAll('.js-wa').forEach(a => { a.href = waLink(); a.target = '_blank'; a.rel = 'noopener'; });
const grid = document.querySelector('#tour-grid');
grid.innerHTML = tours.map((t,i) => `<article class="tour-card reveal"><div class="tour-photo"><img loading="lazy" src="${t.image}" alt="${t.name}, tour en Cusco"><span class="tour-label">${t.label}</span><h3 class="tour-name">${t.name}</h3></div><div class="tour-body"><div class="tour-meta"><span>${t.duration}</span><span>${t.difficulty}</span><span>${t.altitude}</span></div><p>${t.desc}</p><div class="tour-actions"><button data-tour="${i}">Ver experiencia →</button><a class="small-wa" target="_blank" href="${waLink(`Hola, AURITIKA EXPERIENCE. Quisiera información sobre el tour ${t.name}.`)}">WhatsApp</a></div></div></article>`).join('');
const faqList = document.querySelector('#faq-list');
faqList.innerHTML = faq.map(([q,a]) => `<article class="faq-item"><button class="faq-question" aria-expanded="false">${q}<b>+</b></button><div class="faq-answer"><p>${a}</p></div></article>`).join('');
document.querySelectorAll('.faq-question').forEach(button => button.addEventListener('click', () => { const item = button.parentElement; document.querySelectorAll('.faq-item.open').forEach(open => { if(open !== item){open.classList.remove('open');open.querySelector('button').setAttribute('aria-expanded','false')} }); item.classList.toggle('open');button.setAttribute('aria-expanded',item.classList.contains('open')); }));
const header = document.querySelector('#header'); window.addEventListener('scroll', () => header.classList.toggle('scrolled',scrollY > 25));
const menu = document.querySelector('.nav'), toggle = document.querySelector('.menu-toggle'); toggle.addEventListener('click', () => { menu.classList.toggle('open');toggle.setAttribute('aria-expanded',menu.classList.contains('open'));document.body.style.overflow=menu.classList.contains('open')?'hidden':''; }); menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.body.style.overflow=''}));
const observer = new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.12}); document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const tourModal = document.querySelector('#tour-modal');
function showTour(i){ const t=tours[i]; document.querySelector('#tour-detail').innerHTML=`<div class="modal-hero"><img src="${t.image}" alt="${t.name}"><h2>${t.name}</h2></div><div class="detail-copy"><div class="detail-meta"><span>Duración · ${t.duration}</span><span>Altitud · ${t.altitude}</span><span>Dificultad · ${t.difficulty}</span></div><h3>Descripción</h3><p>${t.desc}</p><h3>Lugares a visitar</h3><p>${t.places}</p><h3>Itinerario</h3><p>La ruta y los horarios se coordinan para tu experiencia. Te compartiremos el detalle actualizado según tu fecha de viaje.</p><h3>¿Qué incluye?</h3><ul><li>Coordinación previa de tu experiencia.</li><li>Acompañamiento según el recorrido seleccionado.</li><li>Información actualizada antes de viajar.</li></ul><h3>Recomendaciones</h3><p>Lleva ropa adecuada para el clima, agua, protector solar y consulta con nosotros cualquier requerimiento particular.</p><a class="button navy" target="_blank" href="${waLink(`Hola, AURITIKA EXPERIENCE. Quisiera información sobre el tour ${t.name}.`)}">Consultar por WhatsApp <span>→</span></a></div>`; openModal(tourModal); }
grid.addEventListener('click', e=>{const btn=e.target.closest('[data-tour]');if(btn)showTour(btn.dataset.tour)});
function openModal(modal){modal.classList.add('visible');document.body.style.overflow='hidden';modal.querySelector('.modal-close').focus()}; function closeModal(modal){modal.classList.remove('visible');document.body.style.overflow=''}; document.querySelectorAll('.modal').forEach(m=>{m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.modal-close'))closeModal(m)})});
document.querySelector('#claims-open').addEventListener('click',()=>openModal(document.querySelector('#claims-modal'))); document.querySelector('#claims-form').addEventListener('submit',e=>{e.preventDefault();e.target.hidden=true;document.querySelector('.form-message').hidden=false}); document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.modal.visible').forEach(closeModal);menu.classList.remove('open');document.body.style.overflow=''}});
